---
# ansible/roles/wyoming/handlers/main.yml

- name: restart wyoming-porcupine1
  ansible.builtin.systemd:
    name: wyoming-porcupine1.service
    state: restarted
    scope: user
    daemon_reload: yes

- name: restart wyoming-whisper
  ansible.builtin.systemd:
    name: wyoming-whisper.service
    state: restarted
    scope: user
    daemon_reload: yes

- name: restart wyoming-piper
  ansible.builtin.systemd:
    name: wyoming-piper.service
    state: restarted
    scope: user
    daemon_reload: yes

- name: restart wyoming-satellite
  ansible.builtin.systemd:
    name: wyoming-satellite.service
    state: restarted
    scope: user
    daemon_reload: yes
