---
- name: Uninstall unattended-upgrades to prevent unexpected system changes
  become: yes
  ansible.builtin.apt:
    name: unattended-upgrades
    state: absent

- name: Install essential system packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - i2c-tools
    - alsa-utils
    - python3-gpiozero
    # Python system-level libraries for hardware access and core functions
    - python3-spidev
    - python3-smbus2
    - python3-pil
    - python3-numpy
    - python3-requests
    - python3-pydbus
    - kitty-terminfo

