---
- name: Install wyoming-porcupine1
  ansible.builtin.pip:
    name:
      - wyoming-porcupine1
      - audioop-lts
    virtualenv: "{{ mediaplayer_home }}/wyoming/porcupine1"
    virtualenv_command: "python3 -m venv"
    state: present

- name: Deploy wyoming-porcupine1.service
  ansible.builtin.template:
    src: wyoming-porcupine1.service.j2
    dest: "{{ mediaplayer_home }}/.config/systemd/user/wyoming-porcupine1.service"
    mode: '0644'
  notify: restart wyoming-porcupine1
