---
- name: Install wyoming-satellite
  ansible.builtin.pip:
    name: "wyoming-satellite"
    virtualenv: "{{ mediaplayer_home }}/wyoming/satellite"
    virtualenv_command: "python3 -m venv"
    state: present

- name: Deploy event scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ mediaplayer_home }}/wyoming/satellite/{{ item }}"
    mode: '0755'
  loop:
    - awake.sh
    - done.sh
    - transcript.sh
    - tts-start.sh

- name: Deploy wyoming-satellite.service
  ansible.builtin.template:
    src: wyoming-satellite.service.j2
    dest: "{{ mediaplayer_home }}/.config/systemd/user/wyoming-satellite.service"
    mode: '0644'
  notify: restart wyoming-satellite
