---
- name: Enable and start Wyoming services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
    scope: user
    daemon_reload: yes
  loop:
    - wyoming-porcupine1.service
    - wyoming-whisper.service
    - wyoming-piper.service
    - wyoming-satellite.service
