---
- name: Create wyoming-whisper venv
  ansible.builtin.command:
    cmd: "python3 -m venv {{ mediaplayer_home }}/wyoming/whisper"
    creates: "{{ mediaplayer_home }}/wyoming/whisper/bin/python"

- name: Install wyoming-faster-whisper
  ansible.builtin.pip:
    name:
      - wyoming-faster-whisper
      - audioop-lts
    virtualenv: "{{ mediaplayer_home }}/wyoming/whisper"
    state: present

- name: Deploy wyoming-whisper.service
  ansible.builtin.template:
    src: wyoming-whisper.service.j2
    dest: "{{ mediaplayer_home }}/.config/systemd/user/wyoming-whisper.service"
    mode: '0644'
  notify: restart wyoming-whisper
